apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "explorer.fullname" . }}-crypto4
  labels:
    app: {{ template "explorer.name" . }}
    chart: {{ template "explorer.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  {{- (.Files.Glob "crypto-config/peerOrganizations/peersample.example.com/users/Admin@peersample.example.com/msp/signcerts/Adminpeersampleexamplecom-cert.pem").AsConfig | nindent 2 }}


